Directory content has not changed. No need to rebuild.
2024-10-29 22:28:19,166	INFO worker.py:1807 -- Started a local Ray instance. View the dashboard at [1m[32mhttp://127.0.0.1:8265 [39m[22m
wandb: Currently logged in as: liujay (liujay-National University of Singapore Students' Union). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.18.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/marmot/ljh/LMAPF/wandb/run-20241029_222824-ksxq5rn3
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run peachy-armadillo-20
wandb: ‚≠êÔ∏è View project at https://wandb.ai/liujay-National%20University%20of%20Singapore%20Students%27%20Union/LMAPF
wandb: üöÄ View run at https://wandb.ai/liujay-National%20University%20of%20Singapore%20Students%27%20Union/LMAPF/runs/ksxq5rn3
wandb: ERROR Error while calling W&B API: context deadline exceeded (<Response [500]>)
*** SIGTERM received at time=1730263756 on cpu 17 ***
PC: @     0x75a28d091117  (unknown)  (unknown)
    @     0x75a28d042520  (unknown)  (unknown)
    @ ... and at least 1 more frames
[2024-10-30 11:49:16,833 E 3806922 3806922] logging.cc:440: *** SIGTERM received at time=1730263756 on cpu 17 ***
[2024-10-30 11:49:16,833 E 3806922 3806922] logging.cc:440: PC: @     0x75a28d091117  (unknown)  (unknown)
[2024-10-30 11:49:16,833 E 3806922 3806922] logging.cc:440:     @     0x75a28d042520  (unknown)  (unknown)
[2024-10-30 11:49:16,833 E 3806922 3806922] logging.cc:440:     @ ... and at least 1 more frames
wandb: Waiting for W&B process to finish... (success).
wandb: - 0.001 MB of 0.017 MB uploaded (0.000 MB deduped)./run.sh: line 29: 3806922 Aborted                 (core dumped) python driver.py
Exception in thread MsgRouterThr:
Traceback (most recent call last):
  File "/home/marmot/miniconda3/envs/ljh/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/marmot/miniconda3/envs/ljh/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/marmot/miniconda3/envs/ljh/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/marmot/miniconda3/envs/ljh/lib/python3.11/site-packages/wandb/sdk/interface/router_queue.py", line 36, in _read_message
    msg = self._response_queue.get(timeout=1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marmot/miniconda3/envs/ljh/lib/python3.11/multiprocessing/queues.py", line 117, in get
    res = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/home/marmot/miniconda3/envs/ljh/lib/python3.11/multiprocessing/connection.py", line 212, in recv_bytes
    self._check_closed()
  File "/home/marmot/miniconda3/envs/ljh/lib/python3.11/multiprocessing/connection.py", line 137, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
Directory content has not changed. No need to rebuild.
2024-10-30 13:34:52,444	INFO worker.py:1807 -- Started a local Ray instance. View the dashboard at [1m[32mhttp://127.0.0.1:8265 [39m[22m
Usage stats collection is disabled.
Welcome to LMAPF!

[33m(raylet)[0m The node with node id: 6fd9e2aed26f9c0e3d4c917625d6a796512855e4fe76b66be8871d3e and address: 172.16.185.204 and node name: 172.16.185.204 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a 	(1) raylet crashes unexpectedly (OOM, etc.) 
	(2) raylet has lagging heartbeats due to slow network or busy workload.
Saving Final Model !

Traceback (most recent call last):
  File "/home/marmot/ljh/LMAPF/driver.py", line 182, in <module>
    main(sys.argv)
  File "/home/marmot/ljh/LMAPF/driver.py", line 85, in main
    job_results = ray.get(done_id)
                  ^^^^^^^^^^^^^^^^
  File "/home/marmot/miniconda3/envs/ljh/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/marmot/miniconda3/envs/ljh/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/marmot/miniconda3/envs/ljh/lib/python3.11/site-packages/ray/_private/worker.py", line 2745, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marmot/miniconda3/envs/ljh/lib/python3.11/site-packages/ray/_private/worker.py", line 903, in get_objects
    raise value
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
	class_name: RLRunner
	actor_id: 738deeb51a0c8a0b0800c65c01000000
	pid: 1047531
	namespace: 133de087-d688-4a8e-ab8d-81d0487ab85d
	ip: 172.16.185.204
The actor died because its node has died. Node Id: 6fd9e2aed26f9c0e3d4c917625d6a796512855e4fe76b66be8871d3e
	the actor's node was terminated unexpectedly: dashboard_agent/424238335 failed and raylet fate-shares with it.
[33m(raylet)[0m [2024-10-30 13:35:43,653 E 1047419 1047496] (raylet) agent_manager.cc:83: The raylet exited immediately because one Ray agent failed, agent_name = dashboard_agent/424238335.
[33m(raylet)[0m The raylet fate shares with the agent. This can happen because
[33m(raylet)[0m - The version of `grpcio` doesn't follow Ray's requirement. Agent can segfault with the incorrect `grpcio` version. Check the grpcio version `pip freeze | grep grpcio`.
[33m(raylet)[0m - The agent failed to start because of unexpected error or port conflict. Read the log `cat /tmp/ray/session_latest/logs/{dashboard_agent|runtime_env_agent}.log`. You can find the log file structure here https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#logging-directory-structure.
[33m(raylet)[0m - The agent is killed by the OS (e.g., out of memory).
Directory content has not changed. No need to rebuild.
2024-10-30 13:36:29,995	INFO worker.py:1807 -- Started a local Ray instance. View the dashboard at [1m[32mhttp://127.0.0.1:8265 [39m[22m
wandb: Currently logged in as: liujay (liujay-National University of Singapore Students' Union). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.18.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/marmot/ljh/LMAPF/wandb/run-20241030_133635-s2xbqbbn
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run hollow-dance-21
wandb: ‚≠êÔ∏è View project at https://wandb.ai/liujay-National%20University%20of%20Singapore%20Students%27%20Union/LMAPF
wandb: üöÄ View run at https://wandb.ai/liujay-National%20University%20of%20Singapore%20Students%27%20Union/LMAPF/runs/s2xbqbbn
